export const menu1 = [
  {
    id: "Wonton Soup",
    name: "Wonton Soup",
    price: 3.25,
    priceOptions: [3.25, 5.25],
    size: ["Pt.", "Qt."],
    tags: ["Soup"],
    imageUrl: "/foods/wonton-soup.jpg",
    instructions: "",
  },
  {
    id: "Egg Drop Soup",
    name: "Egg Drop Soup",
    price: 3.1,
    priceOptions: [3.1, 4.95],
    size: ["Pt.", "Qt."],
    tags: ["Soup"],
    imageUrl: "/foods/egg-drop-soup.jpg",
    instructions: "",
  },
  {
    id: "Hot & Sour Soup",
    name: "Hot & Sour Soup",
    price: 3.55,
    priceOptions: [3.55, 5.95],
    size: ["Pt.", "Qt."],
    tags: ["Soup"],
    imageUrl: "/foods/hot-and-sour-soup.jpg",
    instructions: "",
  },
  {
    id: "Chicken Rice Soup",
    name: "Chicken Rice Soup",
    price: 3.1,
    priceOptions: [3.1, 4.95],
    size: ["Pt.", "Qt."],
    tags: ["Soup"],
    imageUrl: "/foods/chicken-rice-soup.jpg",
    instructions: "",
  },
  {
    id: "Vegetable Bean Curd Soup",
    name: "Vegetable Bean Curd Soup",
    price: 6.5,
    priceOptions: [6.5],
    tags: ["Soup"],
    imageUrl: "/foods/vegetable-bean-curd-soup.jpg",
    instructions: "",
  },
  {
    id: "House Special Wonton Soup",
    name: "House Special Wonton Soup",
    price: 6.9,
    priceOptions: [6.9],
    tags: ["Soup"],
    imageUrl: "/foods/house-special-wonton-soup.jpg",
    instructions: "",
  },
  {
    id: "Wonton Egg Drop Soup",
    name: "Wonton Egg Drop Soup",
    price: 3.6,
    priceOptions: [3.6, 5.75],
    size: ["Pt.", "Qt."],
    tags: ["Soup"],
    imageUrl: "/foods/wonton-eggdrop-soup.jpg",
    instructions: "",
  },
  {
    id: "Yat Gaw Mein",
    name: "Yat Gaw Mein",
    price: 6,
    priceOptions: [6, 6],
    addons: ["Chicken", "Roast Pork"],
    tags: ["Soup"],
    imageUrl: "/foods/yat-gaw-mein.jpg",
    instructions: "",
  },
  {
    id: "Seafood Soup",
    name: "Seafood Soup",
    price: 8.4,
    priceOptions: [8.4],
    tags: ["Soup"],
    imageUrl: "/foods/seafood-soup.jpg",
    instructions: "",
  },
  {
    id: "Eggroll",
    name: "Eggroll",
    price: 1.8,
    priceOptions: [1.8],
    tags: ["Appetizer"],
    imageUrl: "/foods/eggroll.jpg",
    instructions: "",
  },
  {
    id: "Shrimp Roll",
    name: "Shrimp Roll",
    price: 1.9,
    priceOptions: [1.9],
    tags: ["Appetizer"],
    imageUrl: "/foods/shrimproll.jpg",
    instructions: "",
  },
  {
    id: "Shanghai Spring Roll(2)",
    name: "Shanghai Spring Roll(2)",
    price: 2.95,
    priceOptions: [2.95],
    tags: ["Appetizer"],
    imageUrl: "/foods/springroll.jpg",
    instructions: "",
  },
  {
    id: "Steamed Dumplings",
    name: "Steamed Dumplings",
    price: 8.45,
    priceOptions: [8.45, 8.45, 8.45],
    addons: ["Pork, Chicken, Vegetable"],
    tags: ["Appetizer"],
    imageUrl: "/foods/steam-dumpling.jpg",
    instructions: "",
  },
  {
    id: "Fried Dumplings",
    name: "Fried Dumplings",
    price: 8.45,
    priceOptions: [8.45, 8.45, 8.45],
    addons: ["Pork, Chicken, Vegetable"],
    tags: ["Appetizer"],
    imageUrl: "/foods/fried-dumpling.jpg",
    instructions: "",
  },
  {
    id: "BBQ Spare Ribs",
    name: "BBQ Spare Ribs",
    price: 8.95,
    priceOptions: [8.95, 14.25],
    size: ["Sm.", "Lg."],
    tags: ["Appetizer"],
    imageUrl: "/foods/bbq-spare-ribs.jpg",
    instructions: "",
  },
  {
    id: "BBQ Beef(4)",
    name: "BBQ Beef(4)",
    price: 8.95,
    priceOptions: [8.95],
    tags: ["Appetizer"],
    imageUrl: "/foods/bbq-beef.jpg",
    instructions: "",
  },
  {
    id: "Fantail Shrimp(2)",
    name: "Fantail Shrimp(2)",
    price: 4.15,
    priceOptions: [4.15],
    tags: ["Appetizer"],
    imageUrl: "/foods/fantail-shrimp.jpg",
    instructions: "",
  },
  {
    id: "Cold Noodles W Seasame Sauce",
    name: "Cold Noodles W Seasame Sauce",
    price: 6.45,
    priceOptions: [6.45],
    tags: ["Appetizer"],
    imageUrl: "/foods/cold-noodle-seasame-sauce.jpg",
    instructions: "",
  },
  {
    id: "BBQ Boneless Ribs",
    name: "BBQ Boneless Ribs",
    price: 8.95,
    priceOptions: [8.95, 14.25],
    size: ["Sm.", "Lg."],
    tags: ["Appetizer"],
    imageUrl: "/foods/bbq-boneless-spare-ribs.jpg",
    instructions: "",
  },
  {
    id: "Cheese Wontons(10)",
    name: "Cheese Wontons(10)",
    price: 6.95,
    priceOptions: [6.95],
    tags: ["Appetizer"],
    imageUrl: "/foods/cheese-wonton.jpg",
    instructions: "",
  },
  {
    id: "Fried Wontons(12)",
    name: "Fried Wontons(12)",
    price: 6.15,
    priceOptions: [6.15, 8.95, 8.95],
    addons: ["w/ Szechuan Sauce(12)", "w/ Garlic Sauce (12)"],
    tags: ["Appetizer"],
    imageUrl: "/foods/fried-wonton.jpg",
    instructions: "",
  },
  {
    id: "Shrimp Toast(4)",
    name: "Shrimp Toast(4)",
    price: 5.65,
    priceOptions: [5.65],
    tags: ["Appetizer"],
    imageUrl: "/foods/shrimp-toast.jpg",
    instructions: "",
  },
  {
    id: "Roast Pork",
    name: "Roast Pork",
    price: 7.45,
    priceOptions: [7.45],
    tags: ["Appetizer"],
    imageUrl: "/foods/roast-pork.jpg",
    instructions: "",
  },
];

export const menu = [
  {
    id: "Wonton Soup",
    name: "Wonton Soup",
    description: "",
    spicy: false,
    price: 3.25,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 2 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.25, 5.25],
    tags: ["Soup"],
    imageUrl: "/foods/wonton-soup.jpg",
    instructions: "",
  },
  {
    id: "Egg Drop Soup",
    name: "Egg Drop Soup",
    description: "",
    spicy: false,
    price: 3.1,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 1.85 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.1, 4.95],
    tags: ["Soup"],
    imageUrl: "/foods/egg-drop-soup.jpg",
    instructions: "",
  },
  {
    id: "Hot & Sour Soup",
    name: "Hot & Sour Soup",
    description: "",
    spicy: true,
    price: 3.55,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 1.3 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.55, 5.95],
    tags: ["Soup"],
    imageUrl: "/foods/hot-and-sour-soup.jpg",
    instructions: "",
  },
  {
    id: "Chicken Rice Soup",
    name: "Chicken Rice Soup",
    description: "",
    spicy: false,
    price: 3.1,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 1.85 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.1, 4.95],
    tags: ["Soup"],
    imageUrl: "/foods/chicken-rice-soup.jpg",
    instructions: "",
  },
  {
    id: "Yat Gaw Mein",
    name: "Yat Gaw Mein",
    description: "",
    spicy: true,
    price: 6,
    required: [
      { id: "Chicken", label: "Chicken", price: 0 },
      { id: "Roast", label: "Roast Pork", price: 1 },
      { id: "Broc", label: "Broc", price: 0 },
      { id: "Carrot", label: "Carrot", price: 1 },
      { id: "Bean", label: "Bean Sprouts", price: 0 },
      { id: "Curry", label: "Curry", price: 1 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [6, 6],
    tags: ["Soup"],
    imageUrl: "/foods/yat-gaw-mein.jpg",
    instructions: "",
  },
];

export const tags = [
  { name: "All", count: 25 },
  { name: "Soup", count: 9 },
  { name: "Appetizer", count: 16 },
  { name: "Chicken", count: 0 },
  { name: "Beef", count: 0 },
  { name: "Lo mein", count: 0 },
];
