export const menu = [
  {
    category: "Soup",
    items: [
      {
        id: "Wonton Soup",
        name: "Wonton Soup",
        description: "A savory broth with wontons filled with pork and shrimp.",
        price: 3.25,
        imageUrl: "/foods/wonton-soup.jpg",
        category: "Soup",
        isSpicy: false,
        required: [
          { id: "Pt.", label: "Pt.", price: 0 },
          { id: "Qt.", label: "Qt.", price: 2 },
        ],
        customizations: [
          { id: "Extra Wontons", label: "Extra Wontons", price: 1.5 },
        ],
        priceOptions: [3.25, 5.25],
        instructions: "",
      },
      {
        id: "Egg Drop Soup",
        name: "Egg Drop Soup",
        description: "A warm soup made with silky egg ribbons.",
        price: 3.1,
        imageUrl: "/foods/egg-drop-soup.jpg",
        category: "Soup",
        isSpicy: false,
        required: [
          { id: "Pt.", label: "Pt.", price: 0 },
          { id: "Qt.", label: "Qt.", price: 1.85 },
        ],
        customizations: [{ id: "Extra Egg", label: "Extra Egg", price: 0.75 }],
        priceOptions: [3.1, 4.95],
        instructions: "",
      },
      {
        id: "Hot & Sour Soup",
        name: "Hot & Sour Soup",
        description:
          "Spicy and tangy soup with mushrooms, tofu, and bamboo shoots.",
        price: 3.55,
        imageUrl: "/foods/hot-and-sour-soup.jpg",
        category: "Soup",
        isSpicy: true,
        required: [
          { id: "Pt.", label: "Pt.", price: 0 },
          { id: "Qt.", label: "Qt.", price: 2.4 },
        ],
        customizations: [
          { id: "Extra Tofu", label: "Extra Tofu", price: 1.25 },
        ],
        priceOptions: [3.55, 5.95],
        instructions: "",
      },
      {
        id: "Chicken Rice Soup",
        name: "Chicken Rice Soup",
        description: "Chicken and rice in a light, flavorful broth.",
        price: 3.1,
        imageUrl: "/foods/chicken-rice-soup.jpg",
        category: "Soup",
        isSpicy: false,
        required: [
          { id: "Pt.", label: "Pt.", price: 0 },
          { id: "Qt.", label: "Qt.", price: 1.85 },
        ],
        customizations: [
          { id: "Extra Chicken", label: "Extra Chicken", price: 1.5 },
        ],
        priceOptions: [3.1, 4.95],
        instructions: "",
      },
      {
        id: "Vegetable Bean Curd Soup",
        name: "Vegetable Bean Curd Soup",
        description:
          "A vegetarian soup with bean curd, mushrooms, and vegetables.",
        price: 6.5,
        imageUrl: "/foods/vegetable-bean-curd-soup.jpg",
        category: "Soup",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [6.5],
        instructions: "",
      },
      {
        id: "House Special Wonton Soup",
        name: "House Special Wonton Soup",
        description: "Special wontons with shrimp and pork in a savory broth.",
        price: 6.9,
        imageUrl: "/foods/house-special-wonton-soup.jpg",
        category: "Soup",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [6.9],
        instructions: "",
      },
      {
        id: "Wonton Egg Drop Soup",
        name: "Wonton Egg Drop Soup",
        description: "A blend of wontons and egg drop soup in one bowl.",
        price: 3.6,
        imageUrl: "/foods/wonton-eggdrop-soup.jpg",
        category: "Soup",
        isSpicy: false,
        required: [
          { id: "Pt.", label: "Pt.", price: 0 },
          { id: "Qt.", label: "Qt.", price: 2.15 },
        ],
        customizations: [
          { id: "Extra Wonton", label: "Extra Wonton", price: 1.5 },
        ],
        priceOptions: [3.6, 5.75],
        instructions: "",
      },
      {
        id: "Yat Gaw Mein",
        name: "Yat Gaw Mein",
        description: "A noodle soup with beef, vegetables, and broth.",
        price: 6,
        imageUrl: "/foods/yat-gaw-mein.jpg",
        category: "Soup",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [6, 6],
        instructions: "",
      },
      {
        id: "Seafood Soup",
        name: "Seafood Soup",
        description:
          "A rich soup made with shrimp, crab, and fish in a savory broth.",
        price: 8.4,
        imageUrl: "/foods/seafood-soup.jpg",
        category: "Soup",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [8.4],
        instructions: "",
      },
    ],
  },
  {
    category: "Appetizer",
    items: [
      {
        id: "Eggroll",
        name: "Eggroll",
        description: "Crispy, deep-fried rolls with a vegetable filling.",
        price: 1.8,
        imageUrl: "/foods/eggroll.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [1.8],
        instructions: "",
      },
      {
        id: "Shrimp Roll",
        name: "Shrimp Roll",
        description: "Crispy rolls filled with seasoned shrimp.",
        price: 1.9,
        imageUrl: "/foods/shrimproll.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [1.9],
        instructions: "",
      },
      {
        id: "Shanghai Spring Roll(2)",
        name: "Shanghai Spring Roll(2)",
        description: "Crispy fried spring rolls with pork and vegetables.",
        price: 2.95,
        imageUrl: "/foods/springroll.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [2.95],
        instructions: "",
      },
      {
        id: "Steamed Dumplings",
        name: "Steamed Dumplings",
        description:
          "Dumplings filled with your choice of pork, chicken, or vegetables.",
        price: 8.45,
        imageUrl: "/foods/steam-dumpling.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [
          { id: "Pork", label: "Pork", price: 0 },
          { id: "Chicken", label: "Chicken", price: 0 },
          { id: "Vegetable", label: "Vegetable", price: 0 },
        ],
        customizations: [],
        priceOptions: [8.45, 8.45, 8.45],
        instructions: "",
      },
      {
        id: "Fried Dumplings",
        name: "Fried Dumplings",
        description:
          "Crispy fried dumplings with a choice of pork, chicken, or vegetable filling.",
        price: 8.45,
        imageUrl: "/foods/fried-dumpling.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [
          { id: "Pork", label: "Pork", price: 0 },
          { id: "Chicken", label: "Chicken", price: 0 },
          { id: "Vegetable", label: "Vegetable", price: 0 },
        ],
        customizations: [],
        priceOptions: [8.45, 8.45, 8.45],
        instructions: "",
      },
      {
        id: "BBQ Spare Ribs",
        name: "BBQ Spare Ribs",
        description: "Tender spare ribs glazed with a smoky BBQ sauce.",
        price: 8.95,
        imageUrl: "/foods/bbq-spare-ribs.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [8.95, 14.25],
        instructions: "",
      },
      {
        id: "BBQ Beef(4)",
        name: "BBQ Beef(4)",
        description: "Grilled beef pieces with a smoky BBQ glaze.",
        price: 8.95,
        imageUrl: "/foods/bbq-beef.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [8.95],
        instructions: "",
      },
      {
        id: "Fantail Shrimp(2)",
        name: "Fantail Shrimp(2)",
        description: "Delicious shrimp with a crispy coating.",
        price: 4.15,
        imageUrl: "/foods/fantail-shrimp.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [4.15],
        instructions: "",
      },
      {
        id: "Cold Noodles W Seasame Sauce",
        name: "Cold Noodles W Seasame Sauce",
        description: "Chilled noodles tossed in a savory sesame sauce.",
        price: 6.45,
        imageUrl: "/foods/cold-noodle-seasame-sauce.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [6.45],
        instructions: "",
      },
      {
        id: "BBQ Boneless Ribs",
        name: "BBQ Boneless Ribs",
        description: "Tender boneless ribs with a rich BBQ flavor.",
        price: 8.95,
        imageUrl: "/foods/bbq-boneless-ribs.jpg",
        category: "Appetizer",
        isSpicy: false,
        required: [],
        customizations: [],
        priceOptions: [8.95, 14.25],
        instructions: "",
      },
    ],
  },
];

export const menu1 = [
  {
    id: "Wonton Soup",
    name: "Wonton Soup",
    description: "",
    spicy: false,
    price: 3.25,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 2 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.25, 5.25],
    tags: ["Soup"],
    imageUrl: "/foods/wonton-soup.jpg",
    instructions: "",
  },
  {
    id: "Egg Drop Soup",
    name: "Egg Drop Soup",
    description: "",
    spicy: false,
    price: 3.1,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 1.85 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.1, 4.95],
    tags: ["Soup"],
    imageUrl: "/foods/egg-drop-soup.jpg",
    instructions: "",
  },
  {
    id: "Hot & Sour Soup",
    name: "Hot & Sour Soup",
    description: "",
    spicy: true,
    price: 3.55,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 1.3 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.55, 5.95],
    tags: ["Soup"],
    imageUrl: "/foods/hot-and-sour-soup.jpg",
    instructions: "",
  },
  {
    id: "Chicken Rice Soup",
    name: "Chicken Rice Soup",
    description: "",
    spicy: false,
    price: 3.1,
    required: [
      { id: "Pt.", label: "Pt.", price: 0 },
      { id: "Qt.", label: "Qt.", price: 1.85 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [3.1, 4.95],
    tags: ["Soup"],
    imageUrl: "/foods/chicken-rice-soup.jpg",
    instructions: "",
  },
  {
    id: "Yat Gaw Mein",
    name: "Yat Gaw Mein",
    description: "",
    spicy: true,
    price: 6,
    required: [
      { id: "Chicken", label: "Chicken", price: 0 },
      { id: "Roast", label: "Roast Pork", price: 1 },
      { id: "Broc", label: "Broc", price: 0 },
      { id: "Carrot", label: "Carrot", price: 1 },
      { id: "Bean", label: "Bean Sprouts", price: 0 },
      { id: "Curry", label: "Curry", price: 1 },
    ],
    customizations: [
      { id: "Sauce", label: "Sauce on Side", price: 0 },
      { id: "ExtraMeat", label: "Extra Meat", price: 1.5 },
    ],
    priceOptions: [6, 6],
    tags: ["Soup"],
    imageUrl: "/foods/yat-gaw-mein.jpg",
    instructions: "",
  },
];

export const tags = [
  { name: "All", count: 25 },
  { name: "Soup", count: 9 },
  { name: "Appetizer", count: 16 },
  { name: "Chicken", count: 0 },
  { name: "Beef", count: 0 },
  { name: "Lo mein", count: 0 },
];
